package io.ledgerpreflight.core;

import io.ledgerpreflight.bytecode.*;
import io.ledgerpreflight.bytecode.BytecodeScanner.*;
import io.ledgerpreflight.evidence.*;
import io.ledgerpreflight.rules.*;
import java.nio.file.*;
import java.io.IOException;
import java.util.*;

public final class AssessmentService {
    public record Options(Path node,Path kit,Path targetCorda,Path tvuJar,Path targetCordapps,Path legacyJars,Path nodeConf,List<Path> tvuResults,Path verifierClasspath,Path rulePack,String networkMode,Path hostEnvironment) {
        public Options(Path node,Path kit,Path targetCorda,Path tvuJar,Path targetCordapps,Path legacyJars,Path nodeConf,List<Path> tvuResults,Path verifierClasspath,Path rulePack){this(node,kit,targetCorda,tvuJar,targetCordapps,legacyJars,nodeConf,tvuResults,verifierClasspath,rulePack,"unknown",null);}
    }
    public Assessment assess(Options options)throws IOException {
        return assess(options, ignored -> {});
    }
    public Assessment assess(Options options,java.util.function.Consumer<String> progress)throws IOException {
        progress.accept("Discovering node…");
        NodeDiscovery.Result discovered=NodeDiscovery.discover(options.node());
        if(discovered.nodes().size()>1)return new Assessment("1","0.1.0","UNKNOWN","unknown","unknown",List.of(f("LP-NODE-001","Multiple node directories discovered","UNKNOWN","CONFIGURATION",discovered.nodes().stream().map(n->n.root().getFileName().toString()).toList(),"No node was selected; compatibility analysis was not run","Supply one discovered node path with --node, or use interactive selection.")),Map.of("node-discovery",discovered));
        NodeDiscovery.Node selected=discovered.nodes().get(0);
        Path selectedConf=options.nodeConf()!=null?options.nodeConf():selected.configs().size()==1?selected.configs().get(0):null;
        options=new Options(selected.root(),options.kit(),options.targetCorda(),options.tvuJar(),options.targetCordapps(),options.legacyJars(),selectedConf,options.tvuResults(),options.verifierClasspath(),options.rulePack(),options.networkMode(),options.hostEnvironment());
        HostEnvironment host=HostEnvironment.inspect(options.hostEnvironment());
        BytecodeScanner scanner=new BytecodeScanner();
        ScanResult current=scanner.scan(options.node());
        progress.accept("Inspecting target runtime…");
        ScanResult target=scanner.scan(options.kit());
        List<Finding> findings=new ArrayList<>();addScanIssues(findings,current,"current-node");addScanIssues(findings,target,"upgrade-kit");
        List<JarInventory> runtimes=Discovery.select(target,"RUNTIME","RUNTIME_LIBRARY","VERIFIER","DRIVER","UNKNOWN");
        if(options.targetCorda()!=null)runtimes=override(scanner,options.targetCorda(),findings);
        List<JarInventory> tvu=options.tvuJar()!=null?Discovery.topLevel(override(scanner,options.tvuJar(),findings)):Discovery.topLevel(Discovery.select(target,"TVU"));
        List<JarInventory> apps=options.targetCordapps()!=null?override(scanner,options.targetCordapps(),findings):Discovery.select(target,"CORDAPP");
        List<JarInventory> legacy=options.legacyJars()!=null?override(scanner,options.legacyJars(),findings):Discovery.select(target,"LEGACY");
        List<JarInventory> oldApps=Discovery.select(current,"CORDAPP","LEGACY_CONTRACT");
        String sourceVersion=runtimeVersion(Discovery.select(current,"RUNTIME")),targetVersion=runtimeVersion(options.targetCorda()!=null?Discovery.topLevel(runtimes):Discovery.select(target,"RUNTIME"));
        if(targetVersion.matches(".*[A-Za-z].*")&&!targetVersion.equals("unknown"))findings.add(f("LP-DISCOVERY-005","Pre-release or qualified runtime version requires validation","UNKNOWN","UPGRADE_PATH",List.of(targetVersion),"Stable release rules may not apply","Supply a supported release runtime and verify version provenance."));
        if(Discovery.topLevel(Discovery.select(target,"RUNTIME")).size()>1 && options.targetCorda()==null)findings.add(f("LP-DISCOVERY-006","Multiple target runtime artifacts were discovered","WARNING","UPGRADE_PATH",List.of("Runtime candidates="+Discovery.topLevel(Discovery.select(target,"RUNTIME")).size()),"Intended runtime identity is ambiguous","Select the intended runtime with --target-corda and supply its dependency set."));
        if(tvu.size()>1)findings.add(f("LP-DISCOVERY-007","Multiple TVU artifacts were discovered","UNKNOWN","TVU",tvu.stream().map(JarInventory::path).toList(),"The validation artifact is ambiguous","Select the intended artifact with --tvu-jar or interactive discovery."));
        if(runtimes.isEmpty()||targetVersion.equals("unknown"))findings.add(f("LP-DISCOVERY-001","Target Corda runtime could not be uniquely identified","UNKNOWN","UPGRADE_PATH",List.of("Target version: "+targetVersion),"Assessment coverage is incomplete","Supply the intended target runtime using --target-corda with version metadata."));
        if(tvu.isEmpty())findings.add(f("LP-DISCOVERY-002","Transaction Validator Utility artifact was not found","BLOCKED","TVU",List.of("No artifact with TVU entry point or contained TVU classes discovered"),"Required upgrade validation cannot be prepared","Add the target TVU JAR to the upgrade kit or use --tvu-jar."));
        for(JarInventory j:tvu)if(!Discovery.version(j).equals("unknown")&&!targetVersion.equals("unknown")&&!Discovery.version(j).equals(targetVersion))findings.add(f("LP-DISCOVERY-003","TVU and target runtime versions disagree","WARNING","TVU",List.of(j.path(),"TVU "+Discovery.version(j),"Target "+targetVersion),"Validation may use a different runtime","Prepare matching intended target artifacts and confirm the TVU environment."));
        if(!oldApps.isEmpty()&&apps.isEmpty())findings.add(f("LP-CORDAPP-004","Target CorDapps are missing","BLOCKED","CORDAPP",List.of(oldApps.size()+" current CorDapps; zero target CorDapps"),"The prepared TVU environment is incomplete","Add rebuilt target CorDapps under upgrade-kit/cordapps."));
        for(JarInventory j:Discovery.select(target,"UNKNOWN"))findings.add(f("LP-DISCOVERY-004","Unclassified target JAR","WARNING","DEPENDENCY",List.of(j.path()),"Artifact role is uncertain; classes are included in the provisional target inventory","Verify artifact purpose and the actual verifier classpath."));
        progress.accept("Analyzing CorDapps and checking legacy-jars…");
        ClasspathEvidence.Result classpath=ClasspathEvidence.read(options.verifierClasspath(),runtimes,legacy);
        progress.accept("Comparing JVM APIs…");
        CompatibilityAnalyzer analyzer=new CompatibilityAnalyzer();
        List<JarInventory> historical=new ArrayList<>(oldApps);historical.addAll(Discovery.select(current,"LEGACY"));
        addCompatibility(findings,analyzer.analyze(historical,runtimes,legacy,classpath.runtimePrecedenceProven()),"current/historical");
        addCompatibility(findings,analyzer.analyze(apps,runtimes,List.of(),false),"target");
        if(historical.isEmpty())addCompatibility(findings,analyzer.analyze(List.of(),runtimes,legacy,classpath.runtimePrecedenceProven()),"target");
        removedClasses(findings,historical,Discovery.select(current,"RUNTIME","RUNTIME_LIBRARY"),runtimes,legacy,apps);
        ConfigAnalyzer.ConfigEvidence config;
        Path conf=selectedConf;
        if(conf==null)findings.add(f("LP-CONFIG-002",selected.configs().isEmpty()?"Node configuration was not discovered":"Multiple candidate configurations discovered","UNKNOWN","CONFIGURATION",selected.configs().stream().map(p->p.getFileName().toString()).toList(),"Effective launch configuration is unknown","Select the active configuration with --node-conf or interactive discovery."));
        try{config=new ConfigAnalyzer().analyze(conf,conf!=null&&conf.toRealPath().startsWith(options.node())?options.node():conf==null?null:conf.toRealPath().getParent());}catch(IOException e){config=new ConfigAnalyzer.ConfigEvidence(null,null,null,false,false,false,List.of("Configuration parsing failed"),"# configuration unavailable\n");findings.add(f("LP-CONFIG-001","Configuration could not be safely parsed","UNKNOWN","CONFIGURATION",List.of(e.getMessage()),"Database and verifier configuration were not assessed","Provide a bounded HOCON file with safe relative includes and resolved required values."));}
        if(config.postgresql()&&config.mixedCase())findings.add(f("LP-DB-001","Mixed-case schema / TVU compatibility risk","WARNING","DATABASE_SCHEMA",List.of("database.schema="+config.schema(),"Hibernate override="+Objects.toString(config.hibernateDefaultSchema(),"not supplied")),"PostgreSQL resolution and normal node startup can succeed while TVU/Hibernate validates a different schema","Validate effective TVU schema resolution on a database copy. Confirm with supported diagnostics before considering an explicit hibernate.default_schema override."));
        if(config.contradictory())findings.add(f("LP-DB-002","Schema declarations disagree","WARNING","DATABASE_SCHEMA",List.of("database.schema="+config.schema(),"JDBC currentSchema="+config.jdbcCurrentSchema(),"Hibernate default_schema="+config.hibernateDefaultSchema()),"Node and TVU persistence paths may resolve different schemas","Reconcile intended schema and collect independent database evidence; do not infer table absence from Hibernate alone."));
        if(config.issues().stream().anyMatch(i->i.startsWith("Unresolved")||i.contains("unsupported expressions")))findings.add(f("LP-CONFIG-003","Configuration values remain unresolved","UNKNOWN","CONFIGURATION",config.issues(),"Effective configuration cannot be established safely","Supply the referenced local include or environment value; no database connection is needed."));
        progress.accept("Evaluating TVU readiness…");
        TvuAnalyzer.TvuEvidence tvuEvidence;
        try{tvuEvidence=new TvuAnalyzer().analyze(options.tvuResults());}catch(IOException e){tvuEvidence=new TvuAnalyzer.TvuEvidence(null,null,null,null,0,Map.of(),false,false,false,List.of(e.getMessage()));findings.add(f("LP-TVU-INPUT","TVU evidence could not be safely analyzed","UNKNOWN","TVU",List.of(e.getMessage()),"Validation success cannot be established","Provide complete, bounded TVU logs and error archives."));}
        if(tvuEvidence.failed()!=null&&tvuEvidence.failed()>0 || !tvuEvidence.rootCauses().isEmpty())findings.add(f("LP-TVU-002","TVU verification failure","BLOCKED","TVU",List.of(Objects.toString(tvuEvidence.processed(),"unknown")+" processed; "+Objects.toString(tvuEvidence.succeeded(),"unknown")+" succeeded; "+Objects.toString(tvuEvidence.failed(),"unknown")+" failures reported",tvuEvidence.detailedRecords()+" detailed records supplied",tvuEvidence.rootCauses().toString()),"Historical transaction verification has not passed","Resolve supplied root causes and rerun the required TVU over the complete transaction set. Detail counts do not establish causes for unsupplied records."));
        if(tvuEvidence.schemaValidationFailure())findings.add(f("LP-DB-003","TVU/Hibernate schema validation failed","BLOCKED","DATABASE_SCHEMA",List.of("Supplied TVU evidence reports schema-validation failure"),"TVU validation is incomplete; this does not prove the physical table is absent or normal node configuration is broken","Compare effective TVU schema, quoting and search_path against independent read-only database evidence on a copy; seek supported vendor guidance."));
        if(!options.tvuResults().isEmpty()&&!tvuEvidence.completeSuccess()&&(tvuEvidence.failed()==null||tvuEvidence.failed()==0))findings.add(f("LP-TVU-003","Successful complete TVU validation is not established","UNKNOWN","TVU",tvuEvidence.issues().isEmpty()?List.of("Missing, inconsistent or incomplete transaction totals"):tvuEvidence.issues(),"Final upgrade readiness cannot be established","Supply one complete TVU run with expected, processed, succeeded and failed counts, and all failure details."));
        Map<String,String> facts=new TreeMap<>();if(!host.plannedTargetJava().equals("UNKNOWN"))facts.put("target.java",host.plannedTargetJava().startsWith("17")?"17":host.plannedTargetJava());
        if(!host.plannedTargetJava().equals("UNKNOWN") && host.targetJavaReadiness().contains("UNVERIFIED"))findings.add(f("LP-HOST-003","Reported target Java is not sufficiently established","UNKNOWN","JAVA",host.observations(),"A major-only or pre-release Java declaration does not establish the supported target runtime","Provide the exact supported Java 17 patch intended for the target environment."));
        if(host.targetJavaReadiness().equals("INCOMPATIBLE"))findings.add(f("LP-HOST-002","Reported target Java does not meet the target requirement","BLOCKED","JAVA",host.observations(),"The planned target Corda environment requires a supported Java 17 patch","Prepare Java 17.0.9 or a later Java 17 patch in the target environment; LedgerPreflight does not modify system Java."));
        if(host.targetJavaReadiness().equals("UNVERIFIED") && !host.currentJava().equals("UNKNOWN") && !host.currentJava().startsWith("17"))findings.add(f("LP-HOST-001","Target Java preparation needs confirmation","WARNING","JAVA",List.of("Current host Java: "+host.currentJava(),"LedgerPreflight private/analyzer Java: "+host.analyzerJava(),"Target Corda requirement: "+host.targetRequiredJava()),"The analyzer can run with its private runtime, but that does not prepare the target node Java environment","Confirm the planned target Java independently; provide --host-environment evidence without replacing the current node Java."));
        facts.put("network.mode",options.networkMode());facts.put("source.version",sourceVersion);facts.put("target.version",targetVersion);facts.put("tvu.present",Boolean.toString(!tvu.isEmpty()));facts.put("legacyJars.present",Boolean.toString(!legacy.isEmpty()));facts.put("legacyContracts.present",Boolean.toString(!Discovery.select(target,"LEGACY_CONTRACT").isEmpty()));
        for(JarInventory app:apps) {
            String min=Discovery.attr(app,"Min-Platform-Version");if(!min.isEmpty() && !min.equals("140"))findings.add(f("LP-CORDAPP-003","Target CorDapp minimum platform differs from 140","WARNING","CORDAPP",List.of(app.path(),"Min-Platform-Version="+min),"Target CorDapp upgrade requirements need validation","Rebuild target CorDapps according to the official 4.12 upgrade guide."));
            if(app.classes().values().stream().anyMatch(c->c.references().stream().anyMatch(r->r.owner().equals("net/corda/core/contracts/HashAttachmentConstraint"))))facts.put("constraints.hashDetected","true");
        }
        List<JarInventory> allApps=new ArrayList<>(historical);allApps.addAll(apps);
        if(allApps.stream().anyMatch(j->j.classes().values().stream().anyMatch(c->c.references().stream().anyMatch(r->r.owner().equals("net/corda/core/contracts/HashAttachmentConstraint")))))facts.put("constraints.hashDetected","true");
        if(allApps.stream().anyMatch(j->j.classes().values().stream().anyMatch(c->c.references().stream().anyMatch(r->r.owner().contains("ContractUpgradeFlow")||r.owner().equals("net/corda/core/contracts/UpgradedContract")))))facts.put("constraints.explicitUpgradeDetected","true");
        for(JarInventory runtime:runtimes){String platform=Discovery.attr(runtime,"Corda-Platform-Version");if(platform.isEmpty())platform=Discovery.attr(runtime,"Platform-Version");if(!platform.isEmpty()&&!platform.equals("140"))facts.put("target.platform",platform);}
        if(historical.stream().anyMatch(AssessmentService::legacyVerifyPattern)||apps.stream().anyMatch(AssessmentService::legacyVerifyPattern))facts.put("verification.legacyPattern","true");
        RuleEngine engine=options.rulePack()==null?new RuleEngine():new RuleEngine().load(options.rulePack());
        for(RuleFinding r:engine.evaluate(facts))findings.add(new Finding(r.id(),r.title(),r.severity(),r.category(),r.status(),r.confidence(),r.source(),r.affectedArtifact(),r.evidence(),r.impact(),r.explanation(),r.nextAction(),r.documentationReference()));
        compareCorDapps(findings,oldApps,apps);
        Map<String,Object> evidence=new TreeMap<>();evidence.put("node-discovery",discovered);evidence.put("environment",Map.of("nodeName",Discovery.displayName(config.safeSettings(),options.node().toAbsolutePath().normalize().getFileName().toString()),"current",Discovery.inventory(current),"sourceVersion",sourceVersion,"targetVersion",targetVersion,"offline",true,"host",host,"rulePackVersion",RuleEngine.PACK_VERSION));evidence.put("upgrade-kit",Discovery.inventory(target));evidence.put("cordapps-current",Discovery.topLevel(oldApps).stream().map(j->Map.of("path",j.path(),"sha256",j.sha256())).toList());evidence.put("cordapps-target",Discovery.topLevel(apps).stream().map(j->Map.of("path",j.path(),"sha256",j.sha256())).toList());evidence.put("runtime-api-delta",analyzer.compare(Discovery.select(current,"RUNTIME","RUNTIME_LIBRARY"),runtimes));evidence.put("internal-api-usage",findings.stream().filter(f->f.category().equals("INTERNAL_API")).toList());evidence.put("legacy-jars-analysis",findings.stream().filter(f->f.category().equals("LEGACY_JARS")).toList());evidence.put("classpath-analysis",classpath);evidence.put("schema-analysis",config);evidence.put("tvu-summary",tvuEvidence);evidence.put("sanitized-node.conf",config.sanitizedConfig());
        findings=findings.stream().distinct().sorted().toList();
        return new Assessment("1","0.1.0",Assessment.readiness(findings,tvuEvidence.completeSuccess(),!options.tvuResults().isEmpty()),sourceVersion,targetVersion,findings,evidence);
    }
    private static boolean legacyVerifyPattern(JarInventory app){return app.classes().values().stream().anyMatch(c->c.references().stream().anyMatch(r->r.name().equals("toLedgerTransaction") && Set.of("net/corda/core/transactions/SignedTransaction","net/corda/core/transactions/WireTransaction","net/corda/core/transactions/TransactionBuilder").contains(r.owner()))&&c.references().stream().anyMatch(r->r.owner().equals("net/corda/core/transactions/LedgerTransaction")&&r.name().equals("verify")));}
    private static void compareCorDapps(List<Finding> findings,List<JarInventory> old,List<JarInventory> target){
        for(JarInventory a:old){String name=Discovery.attr(a,"Cordapp-Contract-Name");List<JarInventory> matches=NodeDiscovery.matches(a,target);
            if(matches.size()!=1){findings.add(f("LP-CORDAPP-005","Current CorDapp has no unique target match","WARNING","CORDAPP",List.of(a.path()),"Rebuild and signing continuity coverage is uncertain","Supply unambiguous manifest identity or matching class-content evidence for target artifacts."));continue;}
            JarInventory b=matches.get(0);
            if(a.sha256().equals(b.sha256()))findings.add(f("LP-CORDAPP-008","Current and target CorDapp bytes are identical","WARNING","CORDAPP",List.of(a.path(),b.path()),"Target rebuild evidence is absent","Confirm the CorDapp has been upgraded appropriately for Corda 4.12 and Java 17."));
            if(!name.isEmpty() && (a.signatureFiles().isEmpty()||b.signatureFiles().isEmpty()))findings.add(f("LP-SIGNING-002","Contract signing continuity is unproven","WARNING","SIGNING",List.of(a.path(),b.path(),"Signature metadata missing"),"Signing-key continuity cannot be established","Verify signed current and target CorDapps and the documented attachment-constraint requirements."));
            if(!a.signatureFiles().equals(b.signatureFiles()))findings.add(f("LP-SIGNING-003","CorDapp signature metadata differs","WARNING","SIGNING",List.of(a.path(),b.path(),"Signature block names differ; signer identity has not been cryptographically established"),"Signing-key continuity requires verification","Verify signatures and compare trusted signer public keys using the official procedure."));
            else if(!a.signatureFiles().isEmpty())findings.add(f("LP-SIGNING-004","Signing continuity needs cryptographic validation","WARNING","SIGNING",List.of(a.path(),"Signature block names are present but do not prove same signing keys"),"Static metadata cannot establish trusted signing identity","Verify current and target JAR signatures and compare signer public keys."));
            if(!name.isEmpty()){try{int av=Integer.parseInt(Discovery.attr(a,"Cordapp-Contract-Version")),bv=Integer.parseInt(Discovery.attr(b,"Cordapp-Contract-Version"));if(bv<=av)findings.add(f("LP-CORDAPP-006","Target contract version did not increase","BLOCKED","CORDAPP",List.of(name+": "+av+" -> "+bv),"Target contracts do not meet the documented upgrade version increment","Increase contract version as required by the official 4.12 upgrade guide."));}catch(NumberFormatException e){findings.add(f("LP-CORDAPP-007","Contract version metadata is incomplete","WARNING","CORDAPP",List.of(name),"Contract version increment cannot be checked","Provide contract version metadata and verify the required increment."));}}
        }
    }
    private static void removedClasses(List<Finding> findings,List<JarInventory> consumers,List<JarInventory> oldRuntime,List<JarInventory> runtime,List<JarInventory> legacy,List<JarInventory> targetApps){Set<String> before=new HashSet<>(),after=new HashSet<>();oldRuntime.forEach(j->before.addAll(j.classes().keySet()));for(var list:List.of(runtime,legacy,targetApps))list.forEach(j->after.addAll(j.classes().keySet()));for(JarInventory j:consumers)for(ClassInfo c:j.classes().values())for(Reference r:c.references())if(before.contains(r.owner())&&!after.contains(r.owner()))findings.add(f("LP-API-006","Previously supplied runtime class is absent from the target kit","BLOCKED","API_COMPATIBILITY",List.of(j.path(),c.name(),r.owner()),"Required historical linkage is unavailable in the supplied target inventory","Supply the complete supported target runtime/dependencies and rerun TVU."));}
    private static List<JarInventory> override(BytecodeScanner s,Path path,List<Finding> findings){ScanResult r=s.scan(path);addScanIssues(findings,r,"override");return r.jars();}
    private static String runtimeVersion(List<JarInventory> jars){List<String> versions=jars.stream().map(Discovery::version).filter(v->!v.equals("unknown")).distinct().toList();return versions.size()==1?versions.get(0):"unknown";}
    private static void addScanIssues(List<Finding> findings,ScanResult scan,String root){for(ScanIssue i:scan.issues())findings.add(f(i.code(),"Input could not be completely scanned","UNKNOWN","SECURITY",List.of(root+"/"+i.path(),i.message()),"Assessment coverage is incomplete","Correct or remove malformed/unsafe supplied inputs and rerun."));}
    private static void addCompatibility(List<Finding> findings,List<CompatibilityAnalyzer.CompatibilityIssue> issues,String scope){for(var i:issues){String category=i.id().startsWith("LP-LEGACY")?"LEGACY_JARS":i.id().startsWith("LP-INTERNAL")?"INTERNAL_API":"API_COMPATIBILITY";findings.add(Finding.of(i.id(),i.message(),i.severity(),category,i.severity().equals("BLOCKED")?"HIGH":"POTENTIAL","RUNTIME_DISCOVERY",scope+"/"+i.evidence().getOrDefault("jar",i.evidence().getOrDefault("legacyJar","runtime")),i.evidence().entrySet().stream().map(e->e.getKey()+": "+e.getValue()).toList(),"Historical or target linkage/verification may fail",i.nextAction()));}}
    private static Finding f(String id,String title,String severity,String category,List<String> evidence,String impact,String next){return Finding.of(id,title,severity,category,severity.equals("BLOCKED")?"HIGH":"POTENTIAL",id.startsWith("LP-DB")?"HEURISTIC":"RUNTIME_DISCOVERY","assessment",evidence,impact,next);}
}
